apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-shop-dev
  namespace: argocd
  finalizers:
    # Delete managed resources before deleting this Application.
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://github.com/sshaurya84/devops_shop.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-shop
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
